stages:
  - prepare
  - build
  - release

variables:
  BUILD_DIR: build

build_images:
  stage: prepare
  tags: [IChem-tag]
  script:
    - cd $CI_PROJECT_DIR
    - podman build -f ci-containers/Containerfile.ubi -t ichem-dev:ubi8 .
    - podman build -f ci-containers/Containerfile.ubuntu -t ichem-dev:ubuntu .
    - podman build -f ci-containers/Containerfile.debian -t ichem-dev:debian .
  rules:
    - when: manual

build_all:
  stage: build
  tags: [IChem-tag]
  script:
    - mkdir -p $CI_PROJECT_DIR/$BUILD_DIR
    - podman run --rm -v $CI_PROJECT_DIR:/IChem:Z -w /IChem/$BUILD_DIR ichem-dev:ubi8 bash -c "cmake .. && make -j\$(nproc) && cp IChem /IChem/IChem_ubi"
    - rm -rf $CI_PROJECT_DIR/$BUILD_DIR/*
    - podman run --rm -v $CI_PROJECT_DIR:/IChem:Z -w /IChem/$BUILD_DIR ichem-dev:ubuntu bash -c "cmake .. && make -j\$(nproc) && cp IChem /IChem/IChem_ubuntu"
    - rm -rf $CI_PROJECT_DIR/$BUILD_DIR/*
    - podman run --rm -v $CI_PROJECT_DIR:/IChem:Z -w /IChem/$BUILD_DIR ichem-dev:debian bash -c "cmake .. && make -j\$(nproc) && cp IChem /IChem/IChem_debian"
  artifacts:
    paths:
      - IChem_ubi
      - IChem_ubuntu
      - IChem_debian
    expire_in: 1 year
  rules:
    - if: '$CI_COMMIT_TAG'
    - when: manual
