  site_name: IC Documentation
  site_description: IChem Documentation
  site_author: IChem Team
  nav:
    - Home: index.md

    - Getting started:
        - Overview: getting-started/index.md
        - Install: getting-started/install.md
        - Quickstart: getting-started/quickstart.md
        - Examples: getting-started/examples.md

    - Commands:
        - Overview: commands/index.md
        - IFP - Interaction Fingerprint : commands/ifp.md
        - ints: commands/ints.md
        - atomprops: commands/atomprops.md
        - grim: commands/grim.md
        - volsite: commands/volsite.md
        - pdbconv: commands/pdbconv.md
        - realign: commands/realign.md
        - sims: commands/sims.md
        - utils: commands/utils.md
      
    - Concepts:
        - Overview: concepts/index.md

    - Reference:
        - Overview: reference/index.md
        
    - Python API:
        - Overview: python-api/index.md
        - Installation: python-api/installation.md
        - Quickstart: python-api/quickstart.md
        - Configuration: python-api/config.md

  theme:
    name: material
    logo: python-api/images/output_interactions.png

    palette:
      - scheme: default
        primary: indigo
        accent: blue
      - scheme: slate
        primary: grey
        accent: blue
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode
    font:
      text: Roboto
      code: Roboto Mono

    features:
      - navigation.tabs
      - navigation.instant
      - navigation.tracking
      - navigation.sections
      # - navigation.expand
      - navigation.top
      - navigation.indexes
      - search.highlight
      - search.share
      - content.code.copy
      - content.tabs.link
      - footer

    footer:
      text: "© 2026 TEST LIT-CNRS"

    language: en

  extra_css:
    - stylesheets/nav.css

  plugins:
    - search

  markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.inlinehilite
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.details

  extra:
    generator: false