  site_name: IChem
  site_description: IChem Documentation
  site_author: IChem Team
  nav:
    - Home: index.md

    - Getting started:
        - Install: getting-started/install.md
        - Quickstart: getting-started/quickstart.md
        - Examples: getting-started/examples.md

    - Commands:
        - Overview: commands/index.md
        - IFP - Interaction Fingerprint : commands/ifp.md
        - ints: commands/ints.md
        - AtomProps: commands/AtomProps.md
        - grim: commands/grim.md
        - Volsite: commands/volsite.md
        - pdbconv: commands/pdbconv.md
        - realign: commands/realign.md
        - sims: commands/sims.md
        - utils: commands/utils.md
      
    - Concepts:
        - Overview: concepts/index.md

    - Reference:
        - Overview: reference/index.md
        
    - Python API:
        - Overview: python-api/index.md
        - Installation: python-api/installation.md
        - Quickstart: python-api/quickstart.md
        - Configuration: python-api/config.md

  theme:
    name: material
    logo: python-api/images/output_interactions.png

    palette:
      - scheme: default
        primary: grey
        accent: blue
      - scheme: slate
        primary: grey
        accent: blue
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode
    font:
      text: Roboto
      code: Roboto Mono

    features:
      - navigation.instant
      - navigation.tracking
      - navigation.sections
      - navigation.expand
      - navigation.top
      - search.highlight
      - search.share
      - content.code.copy
      - content.tabs.link

    language: en

  plugins:
    - search

  markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.inlinehilite
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.details