  site_name: IChem

  nav:
    - Home: index.md

    - Getting started:
        - Install: getting-started/install.md
        - Quickstart: getting-started/quickstart.md
        - Examples: getting-started/examples.md

    - Commands:
        - Overview: commands/index.md
        - IFP - Interaction Fingerprint : commands/ifp.md
        - ints: commands/ints.md
        - AtomProps: commands/AtomProps.md
        - grim: commands/grim.md
        - Volsite: commands/volsite.md
        - pdbconv: commands/pdbconv.md
        - realign: commands/realign.md
        - sims: commands/sims.md
        - utils: commands/utils.md
      
    - Concepts:
        - Overview: concepts/index.md

    - Reference:
        - Overview: reference/index.md
        
    - Python API:
        - Overview: python-api/index.md
        - Installation: python-api/installation.md
        - Quickstart: python-api/quickstart.md
        - Configuration: python-api/config.md


  theme:
    name: material
    palette:
      - scheme: material
        primary: blue
        accent: teal
      - scheme: slate
        primary: blue
        toggle: true
    font:
      text: Roboto
      code: Roboto Mono
  markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.inlinehilite