FROM registry.access.redhat.com/ubi8/ubi:8.8

# Python (3.9) and dev headers
RUN dnf module enable -y python39 && \
    dnf install -y \
        gcc-c++ \
        cmake \
        make \
        python39 \
        python39-devel \
    && dnf clean all

# We make sure /usr/bin/python3 is Python 3.9
RUN ln -sf /usr/bin/python3.9 /usr/bin/python3