FROM debian:12

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        cmake \
        g++ \
        make \
        python3 \
        python3-dev \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*