#include "headers/ICTools/switch.h"
#include "headers/ICTools/ifp_module.hpp"

using namespace std;

void IChemSwitch::helpIFP() const {
    cout
        << "IFP - Interaction FingerPrint\n"
        << "Usage: IChem [options] IFP protein ligand\n"
        << "       IChem [options] IFP protein ligand ligand_ref\n"
        << "       IChem [options] IFP protein1 ligand1 protein2 ligand2\n"
        << "\n"
        << "Note:\n"
        << "  * All options must appear before the keyword IFP\n"
        << "  * Distance thresholds accept at most 3 decimals\n"
        << "\n"
        << "Fingerprint formats:\n"
        << "  --old        Legacy 7 bit format: [basic]\n"
        << "  Default      11 bit format: [basic][pi-cation][metal][weakh]\n"
        << "               Structure always kept (unused bits = 0)\n"
        << "\n"
        << "Main Options: (One at a time)\n"
        << "  --all        Compute all interactions\n"
        << "  --basic      Compute only basic interactions (others = 0)\n"
        << "  --picat      Compute only the Pi-cation bit (others = 0)\n"
        << "  --metal      Compute only the Metal/Acceptor bit (others = 0)\n"
        << "  --weakh      Compute only Weak H-bond bits (others = 0)\n"
        << "  --old        Use legacy 7 bit output\n"
        << "\n"
        << "Thresholds (maximum distances):\n"
        << "  -D_Hb    N (3.5)   Hbond\n"
        << "  -D_Hyd   N (4.5)   Hydrophobic\n"
        << "  -D_Io    N (4.0)   Ionic\n"
        << "  -D_Me    N (2.8)   Metal/Acceptor\n"
        << "  -D_Ar    N (5.0)   Aromatic\n"
        << "  -D_Pic   N (5.0)   Pi-Cation\n"
        << "  -D_WHb   N (3.5)   Weak Hbond\n"
        << "\n"
        << "Thresholds (minimum distances):\n"
        << "  -d_Hb    N (2.3)\n"
        << "  -d_Hyd   N (3.2)\n"
        << "  -d_Io    N (2.3)\n"
        << "  -d_Me    N (1.8)\n"
        << "  -d_Ar    N (3.2)\n"
        << "  -d_Pic   N (3.0)\n"
        << "  -d_WHb   N (2.3)\n"
        << "\n"
        << "Angles (degrees):\n"
        << "  -a_H     N (180°)   Hbond angle\n"
        << "  -at_H    N (60°)    Hbond tolerance\n"
        << "  -a_ArFF  N (180°)   Aromatic Face-to-Face\n"
        << "  -at_ArFF N (30°)    FF tolerance\n"
        << "  -a_ArEF  N (90°)    Aromatic Edge-to-Face\n"
        << "  -at_ArEF N (60°)    EF tolerance\n"
        << "  -a_Pic   N (180°)   Pi-Cation angle\n"
        << "  -at_Pic  N (30°)    Pi-Cation tolerance\n"
        << "\n"
        << "Examples:\n"
        << "  IChem --old IFP protein.mol2 ligand.mol2\n"
        << "  IChem --weakh IFP protein.mol2 ligand.mol2 ligand_ref.mol2\n"
        << "  IChem -d_Hyd 3.34 -D_Hyd 4.81 --basic IFP protein1.mol2 ligand1.mol2 protein2.mol2 ligand2.mol2\n"
        << "\n"
        << "---------------------------------------------------------------------------\n\n";
}

void IChemSwitch::IFP() const {
    IFPModule::runIFP(Input_Values, Opt_Values);
}
