IChem --extended IFP ../../dataset/protlig/1H9Z_1_7_protein.mol2 ../../dataset/protlig/1H9Z_1_7_ligand.mol2 > extended/1H9Z_1_7.ifp
IChem --extended IFP ../../dataset/protlig/1HNN_1_2_protein.mol2 ../../dataset/protlig/1HNN_1_2_ligand.mol2 > extended/1HNN_1_2.ifp
IChem --extended IFP ../../dataset/protlig/1HT8_1_15_protein.mol2 ../../dataset/protlig/1HT8_1_15_ligand.mol2 > extended/1HT8_1_15.ifp
IChem --extended IFP ../../dataset/protlig/1JHA_1_2_protein.mol2 ../../dataset/protlig/1JHA_1_2_ligand.mol2 > extended/1JHA_1_2.ifp
IChem --extended IFP ../../dataset/protlig/1JHO_1_1_protein.mol2 ../../dataset/protlig/1JHO_1_1_ligand.mol2 > extended/1JHO_1_1.ifp
IChem --extended IFP ../../dataset/protlig/1JHV_1_2_protein.mol2 ../../dataset/protlig/1JHV_1_2_ligand.mol2 > extended/1JHV_1_2.ifp
IChem --extended IFP ../../dataset/protlig/1K4H_1_1_protein.mol2 ../../dataset/protlig/1K4H_1_1_ligand.mol2 > extended/1K4H_1_1.ifp
IChem --extended IFP ../../dataset/protlig/1L2S_2_1_protein.mol2 ../../dataset/protlig/1L2S_2_1_ligand.mol2 > extended/1L2S_2_1.ifp
IChem --extended IFP ../../dataset/protlig/1L4H_1_2_protein.mol2 ../../dataset/protlig/1L4H_1_2_ligand.mol2 > extended/1L4H_1_2.ifp
IChem --extended IFP ../../dataset/protlig/1L4M_1_2_protein.mol2 ../../dataset/protlig/1L4M_1_2_ligand.mol2 > extended/1L4M_1_2.ifp
IChem --extended IFP ../../dataset/protlig/1L4N_1_3_protein.mol2 ../../dataset/protlig/1L4N_1_3_ligand.mol2 > extended/1L4N_1_3.ifp
IChem --extended IFP ../../dataset/protlig/1N2B_1_4_protein.mol2 ../../dataset/protlig/1N2B_1_4_ligand.mol2 > extended/1N2B_1_4.ifp
IChem --extended IFP ../../dataset/protlig/1N2J_1_5_protein.mol2 ../../dataset/protlig/1N2J_1_5_ligand.mol2 > extended/1N2J_1_5.ifp
IChem --extended IFP ../../dataset/protlig/1OIF_1_1_protein.mol2 ../../dataset/protlig/1OIF_1_1_ligand.mol2 > extended/1OIF_1_1.ifp
IChem --extended IFP ../../dataset/protlig/1OIF_2_1_protein.mol2 ../../dataset/protlig/1OIF_2_1_ligand.mol2 > extended/1OIF_2_1.ifp
IChem --extended IFP ../../dataset/protlig/1P44_1_3_protein.mol2 ../../dataset/protlig/1P44_1_3_ligand.mol2 > extended/1P44_1_3.ifp
IChem --extended IFP ../../dataset/protlig/1P44_1_4_protein.mol2 ../../dataset/protlig/1P44_1_4_ligand.mol2 > extended/1P44_1_4.ifp
IChem --extended IFP ../../dataset/protlig/1P45_1_3_protein.mol2 ../../dataset/protlig/1P45_1_3_ligand.mol2 > extended/1P45_1_3.ifp
IChem --extended IFP ../../dataset/protlig/1P45_1_5_protein.mol2 ../../dataset/protlig/1P45_1_5_ligand.mol2 > extended/1P45_1_5.ifp
IChem --extended IFP ../../dataset/protlig/1P4F_1_1_protein.mol2 ../../dataset/protlig/1P4F_1_1_ligand.mol2 > extended/1P4F_1_1.ifp
IChem --extended IFP ../../dataset/protlig/1Q4G_1_10_protein.mol2 ../../dataset/protlig/1Q4G_1_10_ligand.mol2 > extended/1Q4G_1_10.ifp
IChem --extended IFP ../../dataset/protlig/1RF9_1_2_protein.mol2 ../../dataset/protlig/1RF9_1_2_ligand.mol2 > extended/1RF9_1_2.ifp
IChem --extended IFP ../../dataset/protlig/1SJ0_1_1_protein.mol2 ../../dataset/protlig/1SJ0_1_1_ligand.mol2 > extended/1SJ0_1_1.ifp
IChem --extended IFP ../../dataset/protlig/1UT6_1_1_protein.mol2 ../../dataset/protlig/1UT6_1_1_ligand.mol2 > extended/1UT6_1_1.ifp
IChem --extended IFP ../../dataset/protlig/1UU3_1_16_protein.mol2 ../../dataset/protlig/1UU3_1_16_ligand.mol2 > extended/1UU3_1_16.ifp
IChem --extended IFP ../../dataset/protlig/1UVR_1_13_protein.mol2 ../../dataset/protlig/1UVR_1_13_ligand.mol2 > extended/1UVR_1_13.ifp
IChem --extended IFP ../../dataset/protlig/1VAF_2_3_protein.mol2 ../../dataset/protlig/1VAF_2_3_ligand.mol2 > extended/1VAF_2_3.ifp
IChem --extended IFP ../../dataset/protlig/1XGI_2_1_protein.mol2 ../../dataset/protlig/1XGI_2_1_ligand.mol2 > extended/1XGI_2_1.ifp
IChem --extended IFP ../../dataset/protlig/1XGJ_2_1_protein.mol2 ../../dataset/protlig/1XGJ_2_1_ligand.mol2 > extended/1XGJ_2_1.ifp
IChem --extended IFP ../../dataset/protlig/1XPC_1_1_protein.mol2 ../../dataset/protlig/1XPC_1_1_ligand.mol2 > extended/1XPC_1_1.ifp
IChem --extended IFP ../../dataset/protlig/1Y2B_1_1_protein.mol2 ../../dataset/protlig/1Y2B_1_1_ligand.mol2 > extended/1Y2B_1_1.ifp
IChem --extended IFP ../../dataset/protlig/1Y2B_2_1_protein.mol2 ../../dataset/protlig/1Y2B_2_1_ligand.mol2 > extended/1Y2B_2_1.ifp
IChem --extended IFP ../../dataset/protlig/1Y5X_1_1_protein.mol2 ../../dataset/protlig/1Y5X_1_1_ligand.mol2 > extended/1Y5X_1_1.ifp
IChem --extended IFP ../../dataset/protlig/1YXV_1_2_protein.mol2 ../../dataset/protlig/1YXV_1_2_ligand.mol2 > extended/1YXV_1_2.ifp
IChem --extended IFP ../../dataset/protlig/1ZKN_1_4_protein.mol2 ../../dataset/protlig/1ZKN_1_4_ligand.mol2 > extended/1ZKN_1_4.ifp
IChem --extended IFP ../../dataset/protlig/1ZSN_1_3_protein.mol2 ../../dataset/protlig/1ZSN_1_3_ligand.mol2 > extended/1ZSN_1_3.ifp
IChem --extended IFP ../../dataset/protlig/2A5U_1_1_protein.mol2 ../../dataset/protlig/2A5U_1_1_ligand.mol2 > extended/2A5U_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2AYL_1_9_protein.mol2 ../../dataset/protlig/2AYL_1_9_ligand.mol2 > extended/2AYL_1_9.ifp
IChem --extended IFP ../../dataset/protlig/2AZR_1_1_protein.mol2 ../../dataset/protlig/2AZR_1_1_ligand.mol2 > extended/2AZR_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2B07_1_1_protein.mol2 ../../dataset/protlig/2B07_1_1_ligand.mol2 > extended/2B07_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2BB7_1_1_protein.mol2 ../../dataset/protlig/2BB7_1_1_ligand.mol2 > extended/2BB7_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2BR1_1_1_protein.mol2 ../../dataset/protlig/2BR1_1_1_ligand.mol2 > extended/2BR1_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2BXA_1_1_protein.mol2 ../../dataset/protlig/2BXA_1_1_ligand.mol2 > extended/2BXA_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2BXA_2_1_protein.mol2 ../../dataset/protlig/2BXA_2_1_ligand.mol2 > extended/2BXA_2_1.ifp
IChem --extended IFP ../../dataset/protlig/2BXP_1_8_protein.mol2 ../../dataset/protlig/2BXP_1_8_ligand.mol2 > extended/2BXP_1_8.ifp
IChem --extended IFP ../../dataset/protlig/2C3L_1_1_protein.mol2 ../../dataset/protlig/2C3L_1_1_ligand.mol2 > extended/2C3L_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2C4H_1_3_protein.mol2 ../../dataset/protlig/2C4H_1_3_ligand.mol2 > extended/2C4H_1_3.ifp
IChem --extended IFP ../../dataset/protlig/2C5F_1_4_protein.mol2 ../../dataset/protlig/2C5F_1_4_ligand.mol2 > extended/2C5F_1_4.ifp
IChem --extended IFP ../../dataset/protlig/2CBU_1_1_protein.mol2 ../../dataset/protlig/2CBU_1_1_ligand.mol2 > extended/2CBU_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2CHX_1_1_protein.mol2 ../../dataset/protlig/2CHX_1_1_ligand.mol2 > extended/2CHX_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2CKM_1_1_protein.mol2 ../../dataset/protlig/2CKM_1_1_ligand.mol2 > extended/2CKM_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2CLX_1_1_protein.mol2 ../../dataset/protlig/2CLX_1_1_ligand.mol2 > extended/2CLX_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2CVD_1_4_protein.mol2 ../../dataset/protlig/2CVD_1_4_ligand.mol2 > extended/2CVD_1_4.ifp
IChem --extended IFP ../../dataset/protlig/2DQM_1_3_protein.mol2 ../../dataset/protlig/2DQM_1_3_ligand.mol2 > extended/2DQM_1_3.ifp
IChem --extended IFP ../../dataset/protlig/2E6A_1_5_protein.mol2 ../../dataset/protlig/2E6A_1_5_ligand.mol2 > extended/2E6A_1_5.ifp
IChem --extended IFP ../../dataset/protlig/2E6F_1_3_protein.mol2 ../../dataset/protlig/2E6F_1_3_ligand.mol2 > extended/2E6F_1_3.ifp
IChem --extended IFP ../../dataset/protlig/2E6F_1_5_protein.mol2 ../../dataset/protlig/2E6F_1_5_ligand.mol2 > extended/2E6F_1_5.ifp
IChem --extended IFP ../../dataset/protlig/2EVO_1_1_protein.mol2 ../../dataset/protlig/2EVO_1_1_ligand.mol2 > extended/2EVO_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2F6W_1_6_protein.mol2 ../../dataset/protlig/2F6W_1_6_ligand.mol2 > extended/2F6W_1_6.ifp
IChem --extended IFP ../../dataset/protlig/2F8Z_1_1_protein.mol2 ../../dataset/protlig/2F8Z_1_1_ligand.mol2 > extended/2F8Z_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2F94_1_2_protein.mol2 ../../dataset/protlig/2F94_1_2_ligand.mol2 > extended/2F94_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2FEU_1_2_protein.mol2 ../../dataset/protlig/2FEU_1_2_ligand.mol2 > extended/2FEU_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2FWY_1_1_protein.mol2 ../../dataset/protlig/2FWY_1_1_ligand.mol2 > extended/2FWY_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2FZ8_1_2_protein.mol2 ../../dataset/protlig/2FZ8_1_2_ligand.mol2 > extended/2FZ8_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2G72_1_2_protein.mol2 ../../dataset/protlig/2G72_1_2_ligand.mol2 > extended/2G72_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2G8N_1_1_protein.mol2 ../../dataset/protlig/2G8N_1_1_ligand.mol2 > extended/2G8N_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2G8N_2_1_protein.mol2 ../../dataset/protlig/2G8N_2_1_ligand.mol2 > extended/2G8N_2_1.ifp
IChem --extended IFP ../../dataset/protlig/2GFJ_1_5_protein.mol2 ../../dataset/protlig/2GFJ_1_5_ligand.mol2 > extended/2GFJ_1_5.ifp
IChem --extended IFP ../../dataset/protlig/2GFK_1_3_protein.mol2 ../../dataset/protlig/2GFK_1_3_ligand.mol2 > extended/2GFK_1_3.ifp
IChem --extended IFP ../../dataset/protlig/2GFK_2_2_protein.mol2 ../../dataset/protlig/2GFK_2_2_ligand.mol2 > extended/2GFK_2_2.ifp
IChem --extended IFP ../../dataset/protlig/2GG0_1_1_protein.mol2 ../../dataset/protlig/2GG0_1_1_ligand.mol2 > extended/2GG0_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2GG8_1_1_protein.mol2 ../../dataset/protlig/2GG8_1_1_ligand.mol2 > extended/2GG8_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2GGB_1_1_protein.mol2 ../../dataset/protlig/2GGB_1_1_ligand.mol2 > extended/2GGB_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2GM9_1_1_protein.mol2 ../../dataset/protlig/2GM9_1_1_ligand.mol2 > extended/2GM9_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2H4K_1_1_protein.mol2 ../../dataset/protlig/2H4K_1_1_ligand.mol2 > extended/2H4K_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2HB1_1_1_protein.mol2 ../../dataset/protlig/2HB1_1_1_ligand.mol2 > extended/2HB1_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2HB9_1_3_protein.mol2 ../../dataset/protlig/2HB9_1_3_ligand.mol2 > extended/2HB9_1_3.ifp
IChem --extended IFP ../../dataset/protlig/2HPT_1_1_protein.mol2 ../../dataset/protlig/2HPT_1_1_ligand.mol2 > extended/2HPT_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2IJ7_4_2_protein.mol2 ../../dataset/protlig/2IJ7_4_2_ligand.mol2 > extended/2IJ7_4_2.ifp
IChem --extended IFP ../../dataset/protlig/2IKH_1_2_protein.mol2 ../../dataset/protlig/2IKH_1_2_ligand.mol2 > extended/2IKH_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2INZ_1_2_protein.mol2 ../../dataset/protlig/2INZ_1_2_ligand.mol2 > extended/2INZ_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2IS7_1_2_protein.mol2 ../../dataset/protlig/2IS7_1_2_ligand.mol2 > extended/2IS7_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2J7C_1_1_protein.mol2 ../../dataset/protlig/2J7C_1_1_ligand.mol2 > extended/2J7C_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2JJ3_1_1_protein.mol2 ../../dataset/protlig/2JJ3_1_1_ligand.mol2 > extended/2JJ3_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2JJ3_1_2_protein.mol2 ../../dataset/protlig/2JJ3_1_2_ligand.mol2 > extended/2JJ3_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2OHP_1_4_protein.mol2 ../../dataset/protlig/2OHP_1_4_ligand.mol2 > extended/2OHP_1_4.ifp
IChem --extended IFP ../../dataset/protlig/2OJT_2_3_protein.mol2 ../../dataset/protlig/2OJT_2_3_ligand.mol2 > extended/2OJT_2_3.ifp
IChem --extended IFP ../../dataset/protlig/2OL4_1_4_protein.mol2 ../../dataset/protlig/2OL4_1_4_ligand.mol2 > extended/2OL4_1_4.ifp
IChem --extended IFP ../../dataset/protlig/2OYU_1_3_protein.mol2 ../../dataset/protlig/2OYU_1_3_ligand.mol2 > extended/2OYU_1_3.ifp
IChem --extended IFP ../../dataset/protlig/2PDG_1_2_protein.mol2 ../../dataset/protlig/2PDG_1_2_ligand.mol2 > extended/2PDG_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2PE0_1_3_protein.mol2 ../../dataset/protlig/2PE0_1_3_ligand.mol2 > extended/2PE0_1_3.ifp
IChem --extended IFP ../../dataset/protlig/2Q92_1_1_protein.mol2 ../../dataset/protlig/2Q92_1_1_ligand.mol2 > extended/2Q92_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2QA6_1_2_protein.mol2 ../../dataset/protlig/2QA6_1_2_ligand.mol2 > extended/2QA6_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2QBR_1_1_protein.mol2 ../../dataset/protlig/2QBR_1_1_ligand.mol2 > extended/2QBR_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2QS1_1_3_protein.mol2 ../../dataset/protlig/2QS1_1_3_ligand.mol2 > extended/2QS1_1_3.ifp
IChem --extended IFP ../../dataset/protlig/2QS3_2_3_protein.mol2 ../../dataset/protlig/2QS3_2_3_ligand.mol2 > extended/2QS3_2_3.ifp
IChem --extended IFP ../../dataset/protlig/2QXM_1_2_protein.mol2 ../../dataset/protlig/2QXM_1_2_ligand.mol2 > extended/2QXM_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2QYN_1_2_protein.mol2 ../../dataset/protlig/2QYN_1_2_ligand.mol2 > extended/2QYN_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2QZR_1_1_protein.mol2 ../../dataset/protlig/2QZR_1_1_ligand.mol2 > extended/2QZR_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2R59_1_1_protein.mol2 ../../dataset/protlig/2R59_1_1_ligand.mol2 > extended/2R59_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2V58_1_1_protein.mol2 ../../dataset/protlig/2V58_1_1_ligand.mol2 > extended/2V58_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2V5Z_1_4_protein.mol2 ../../dataset/protlig/2V5Z_1_4_ligand.mol2 > extended/2V5Z_1_4.ifp
IChem --extended IFP ../../dataset/protlig/2V61_1_1_protein.mol2 ../../dataset/protlig/2V61_1_1_ligand.mol2 > extended/2V61_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2V61_1_2_protein.mol2 ../../dataset/protlig/2V61_1_2_ligand.mol2 > extended/2V61_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2VA7_1_4_protein.mol2 ../../dataset/protlig/2VA7_1_4_ligand.mol2 > extended/2VA7_1_4.ifp
IChem --extended IFP ../../dataset/protlig/2VCQ_1_2_protein.mol2 ../../dataset/protlig/2VCQ_1_2_ligand.mol2 > extended/2VCQ_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2VCW_1_3_protein.mol2 ../../dataset/protlig/2VCW_1_3_ligand.mol2 > extended/2VCW_1_3.ifp
IChem --extended IFP ../../dataset/protlig/2VCX_2_4_protein.mol2 ../../dataset/protlig/2VCX_2_4_ligand.mol2 > extended/2VCX_2_4.ifp
IChem --extended IFP ../../dataset/protlig/2VJB_1_2_protein.mol2 ../../dataset/protlig/2VJB_1_2_ligand.mol2 > extended/2VJB_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2VRJ_1_1_protein.mol2 ../../dataset/protlig/2VRJ_1_1_ligand.mol2 > extended/2VRJ_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2VX3_1_1_protein.mol2 ../../dataset/protlig/2VX3_1_1_ligand.mol2 > extended/2VX3_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2W6M_2_1_protein.mol2 ../../dataset/protlig/2W6M_2_1_ligand.mol2 > extended/2W6M_2_1.ifp
IChem --extended IFP ../../dataset/protlig/2W6Z_1_1_protein.mol2 ../../dataset/protlig/2W6Z_1_1_ligand.mol2 > extended/2W6Z_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2W70_1_1_protein.mol2 ../../dataset/protlig/2W70_1_1_ligand.mol2 > extended/2W70_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2W71_1_2_protein.mol2 ../../dataset/protlig/2W71_1_2_ligand.mol2 > extended/2W71_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2WBG_1_1_protein.mol2 ../../dataset/protlig/2WBG_1_1_ligand.mol2 > extended/2WBG_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2WF1_1_1_protein.mol2 ../../dataset/protlig/2WF1_1_1_ligand.mol2 > extended/2WF1_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2WI3_1_1_protein.mol2 ../../dataset/protlig/2WI3_1_1_ligand.mol2 > extended/2WI3_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2WIH_2_1_protein.mol2 ../../dataset/protlig/2WIH_2_1_ligand.mol2 > extended/2WIH_2_1.ifp
IChem --extended IFP ../../dataset/protlig/2WMR_1_1_protein.mol2 ../../dataset/protlig/2WMR_1_1_ligand.mol2 > extended/2WMR_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2WO6_2_1_protein.mol2 ../../dataset/protlig/2WO6_2_1_ligand.mol2 > extended/2WO6_2_1.ifp
IChem --extended IFP ../../dataset/protlig/2WPA_1_2_protein.mol2 ../../dataset/protlig/2WPA_1_2_ligand.mol2 > extended/2WPA_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2X8D_1_1_protein.mol2 ../../dataset/protlig/2X8D_1_1_ligand.mol2 > extended/2X8D_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2XFP_1_4_protein.mol2 ../../dataset/protlig/2XFP_1_4_ligand.mol2 > extended/2XFP_1_4.ifp
IChem --extended IFP ../../dataset/protlig/2XFQ_1_1_protein.mol2 ../../dataset/protlig/2XFQ_1_1_ligand.mol2 > extended/2XFQ_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2XP5_1_2_protein.mol2 ../../dataset/protlig/2XP5_1_2_ligand.mol2 > extended/2XP5_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2XP7_1_1_protein.mol2 ../../dataset/protlig/2XP7_1_1_ligand.mol2 > extended/2XP7_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2XPA_1_2_protein.mol2 ../../dataset/protlig/2XPA_1_2_ligand.mol2 > extended/2XPA_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2Y00_1_8_protein.mol2 ../../dataset/protlig/2Y00_1_8_ligand.mol2 > extended/2Y00_1_8.ifp
IChem --extended IFP ../../dataset/protlig/2Y01_1_8_protein.mol2 ../../dataset/protlig/2Y01_1_8_ligand.mol2 > extended/2Y01_1_8.ifp
IChem --extended IFP ../../dataset/protlig/2Y02_2_8_protein.mol2 ../../dataset/protlig/2Y02_2_8_ligand.mol2 > extended/2Y02_2_8.ifp
IChem --extended IFP ../../dataset/protlig/2YEK_1_1_protein.mol2 ../../dataset/protlig/2YEK_1_1_ligand.mol2 > extended/2YEK_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2YEK_1_2_protein.mol2 ../../dataset/protlig/2YEK_1_2_ligand.mol2 > extended/2YEK_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2YKC_1_1_protein.mol2 ../../dataset/protlig/2YKC_1_1_ligand.mol2 > extended/2YKC_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2YM4_1_1_protein.mol2 ../../dataset/protlig/2YM4_1_1_ligand.mol2 > extended/2YM4_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2Z4B_1_2_protein.mol2 ../../dataset/protlig/2Z4B_1_2_ligand.mol2 > extended/2Z4B_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2ZX5_1_1_protein.mol2 ../../dataset/protlig/2ZX5_1_1_ligand.mol2 > extended/2ZX5_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2ZX6_1_1_protein.mol2 ../../dataset/protlig/2ZX6_1_1_ligand.mol2 > extended/2ZX6_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2ZX7_1_2_protein.mol2 ../../dataset/protlig/2ZX7_1_2_ligand.mol2 > extended/2ZX7_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2ZXA_1_1_protein.mol2 ../../dataset/protlig/2ZXA_1_1_ligand.mol2 > extended/2ZXA_1_1.ifp
IChem --extended IFP ../../dataset/protlig/2ZXA_1_2_protein.mol2 ../../dataset/protlig/2ZXA_1_2_ligand.mol2 > extended/2ZXA_1_2.ifp
IChem --extended IFP ../../dataset/protlig/2ZXD_1_2_protein.mol2 ../../dataset/protlig/2ZXD_1_2_ligand.mol2 > extended/2ZXD_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3AM5_1_2_protein.mol2 ../../dataset/protlig/3AM5_1_2_ligand.mol2 > extended/3AM5_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3ANR_4_1_protein.mol2 ../../dataset/protlig/3ANR_4_1_ligand.mol2 > extended/3ANR_4_1.ifp
IChem --extended IFP ../../dataset/protlig/3AXW_1_1_protein.mol2 ../../dataset/protlig/3AXW_1_1_ligand.mol2 > extended/3AXW_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3B7D_3_2_protein.mol2 ../../dataset/protlig/3B7D_3_2_ligand.mol2 > extended/3B7D_3_2.ifp
IChem --extended IFP ../../dataset/protlig/3BET_1_1_protein.mol2 ../../dataset/protlig/3BET_1_1_ligand.mol2 > extended/3BET_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3BFT_2_1_protein.mol2 ../../dataset/protlig/3BFT_2_1_ligand.mol2 > extended/3BFT_2_1.ifp
IChem --extended IFP ../../dataset/protlig/3BGZ_1_1_protein.mol2 ../../dataset/protlig/3BGZ_1_1_ligand.mol2 > extended/3BGZ_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3BHT_2_1_protein.mol2 ../../dataset/protlig/3BHT_2_1_ligand.mol2 > extended/3BHT_2_1.ifp
IChem --extended IFP ../../dataset/protlig/3C32_1_6_protein.mol2 ../../dataset/protlig/3C32_1_6_ligand.mol2 > extended/3C32_1_6.ifp
IChem --extended IFP ../../dataset/protlig/3C36_1_7_protein.mol2 ../../dataset/protlig/3C36_1_7_ligand.mol2 > extended/3C36_1_7.ifp
IChem --extended IFP ../../dataset/protlig/3CHP_1_3_protein.mol2 ../../dataset/protlig/3CHP_1_3_ligand.mol2 > extended/3CHP_1_3.ifp
IChem --extended IFP ../../dataset/protlig/3CHS_1_2_protein.mol2 ../../dataset/protlig/3CHS_1_2_ligand.mol2 > extended/3CHS_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3DAZ_1_1_protein.mol2 ../../dataset/protlig/3DAZ_1_1_ligand.mol2 > extended/3DAZ_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3DS6_3_1_protein.mol2 ../../dataset/protlig/3DS6_3_1_ligand.mol2 > extended/3DS6_3_1.ifp
IChem --extended IFP ../../dataset/protlig/3E63_1_1_protein.mol2 ../../dataset/protlig/3E63_1_1_ligand.mol2 > extended/3E63_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3E6T_1_3_protein.mol2 ../../dataset/protlig/3E6T_1_3_ligand.mol2 > extended/3E6T_1_3.ifp
IChem --extended IFP ../../dataset/protlig/3E7I_2_3_protein.mol2 ../../dataset/protlig/3E7I_2_3_ligand.mol2 > extended/3E7I_2_3.ifp
IChem --extended IFP ../../dataset/protlig/3E7T_1_4_protein.mol2 ../../dataset/protlig/3E7T_1_4_ligand.mol2 > extended/3E7T_1_4.ifp
IChem --extended IFP ../../dataset/protlig/3EBD_1_3_protein.mol2 ../../dataset/protlig/3EBD_1_3_ligand.mol2 > extended/3EBD_1_3.ifp
IChem --extended IFP ../../dataset/protlig/3EBD_2_3_protein.mol2 ../../dataset/protlig/3EBD_2_3_ligand.mol2 > extended/3EBD_2_3.ifp
IChem --extended IFP ../../dataset/protlig/3EBH_1_1_protein.mol2 ../../dataset/protlig/3EBH_1_1_ligand.mol2 > extended/3EBH_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3EBI_1_1_protein.mol2 ../../dataset/protlig/3EBI_1_1_ligand.mol2 > extended/3EBI_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3EHY_1_1_protein.mol2 ../../dataset/protlig/3EHY_1_1_ligand.mol2 > extended/3EHY_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3F19_1_1_protein.mol2 ../../dataset/protlig/3F19_1_1_ligand.mol2 > extended/3F19_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3F1A_1_1_protein.mol2 ../../dataset/protlig/3F1A_1_1_ligand.mol2 > extended/3F1A_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3F2P_1_1_protein.mol2 ../../dataset/protlig/3F2P_1_1_ligand.mol2 > extended/3F2P_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3F7Z_1_1_protein.mol2 ../../dataset/protlig/3F7Z_1_1_ligand.mol2 > extended/3F7Z_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3F88_1_1_protein.mol2 ../../dataset/protlig/3F88_1_1_ligand.mol2 > extended/3F88_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3FNH_1_2_protein.mol2 ../../dataset/protlig/3FNH_1_2_ligand.mol2 > extended/3FNH_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3FTU_1_1_protein.mol2 ../../dataset/protlig/3FTU_1_1_ligand.mol2 > extended/3FTU_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3FU3_1_2_protein.mol2 ../../dataset/protlig/3FU3_1_2_ligand.mol2 > extended/3FU3_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3FUJ_1_1_protein.mol2 ../../dataset/protlig/3FUJ_1_1_ligand.mol2 > extended/3FUJ_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3FWJ_1_2_protein.mol2 ../../dataset/protlig/3FWJ_1_2_ligand.mol2 > extended/3FWJ_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3G2H_1_1_protein.mol2 ../../dataset/protlig/3G2H_1_1_ligand.mol2 > extended/3G2H_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3G2I_1_1_protein.mol2 ../../dataset/protlig/3G2I_1_1_ligand.mol2 > extended/3G2I_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3G2J_1_1_protein.mol2 ../../dataset/protlig/3G2J_1_1_ligand.mol2 > extended/3G2J_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3G2L_1_1_protein.mol2 ../../dataset/protlig/3G2L_1_1_ligand.mol2 > extended/3G2L_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3G4I_1_2_protein.mol2 ../../dataset/protlig/3G4I_1_2_ligand.mol2 > extended/3G4I_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3G5H_1_2_protein.mol2 ../../dataset/protlig/3G5H_1_2_ligand.mol2 > extended/3G5H_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3GBB_1_1_protein.mol2 ../../dataset/protlig/3GBB_1_1_ligand.mol2 > extended/3GBB_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3H06_12_1_protein.mol2 ../../dataset/protlig/3H06_12_1_ligand.mol2 > extended/3H06_12_1.ifp
IChem --extended IFP ../../dataset/protlig/3H06_2_1_protein.mol2 ../../dataset/protlig/3H06_2_1_ligand.mol2 > extended/3H06_2_1.ifp
IChem --extended IFP ../../dataset/protlig/3H30_1_1_protein.mol2 ../../dataset/protlig/3H30_1_1_ligand.mol2 > extended/3H30_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3I6M_1_1_protein.mol2 ../../dataset/protlig/3I6M_1_1_ligand.mol2 > extended/3I6M_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3IBA_1_1_protein.mol2 ../../dataset/protlig/3IBA_1_1_ligand.mol2 > extended/3IBA_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3ICK_1_2_protein.mol2 ../../dataset/protlig/3ICK_1_2_ligand.mol2 > extended/3ICK_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3ICM_1_1_protein.mol2 ../../dataset/protlig/3ICM_1_1_ligand.mol2 > extended/3ICM_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3ICN_1_1_protein.mol2 ../../dataset/protlig/3ICN_1_1_ligand.mol2 > extended/3ICN_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3IMG_1_1_protein.mol2 ../../dataset/protlig/3IMG_1_1_ligand.mol2 > extended/3IMG_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3IOD_1_1_protein.mol2 ../../dataset/protlig/3IOD_1_1_ligand.mol2 > extended/3IOD_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3IVC_1_1_protein.mol2 ../../dataset/protlig/3IVC_1_1_ligand.mol2 > extended/3IVC_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3JZI_1_2_protein.mol2 ../../dataset/protlig/3JZI_1_2_ligand.mol2 > extended/3JZI_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3K5D_2_1_protein.mol2 ../../dataset/protlig/3K5D_2_1_ligand.mol2 > extended/3K5D_2_1.ifp
IChem --extended IFP ../../dataset/protlig/3KAH_1_2_protein.mol2 ../../dataset/protlig/3KAH_1_2_ligand.mol2 > extended/3KAH_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3KED_1_1_protein.mol2 ../../dataset/protlig/3KED_1_1_ligand.mol2 > extended/3KED_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3KPW_1_4_protein.mol2 ../../dataset/protlig/3KPW_1_4_ligand.mol2 > extended/3KPW_1_4.ifp
IChem --extended IFP ../../dataset/protlig/3KQW_1_2_protein.mol2 ../../dataset/protlig/3KQW_1_2_ligand.mol2 > extended/3KQW_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3KR8_2_1_protein.mol2 ../../dataset/protlig/3KR8_2_1_ligand.mol2 > extended/3KR8_2_1.ifp
IChem --extended IFP ../../dataset/protlig/3KXO_1_2_protein.mol2 ../../dataset/protlig/3KXO_1_2_ligand.mol2 > extended/3KXO_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3KYT_1_1_protein.mol2 ../../dataset/protlig/3KYT_1_1_ligand.mol2 > extended/3KYT_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3L0L_1_1_protein.mol2 ../../dataset/protlig/3L0L_1_1_ligand.mol2 > extended/3L0L_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3LE8_1_1_protein.mol2 ../../dataset/protlig/3LE8_1_1_ligand.mol2 > extended/3LE8_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3LN1_2_2_protein.mol2 ../../dataset/protlig/3LN1_2_2_ligand.mol2 > extended/3LN1_2_2.ifp
IChem --extended IFP ../../dataset/protlig/3LT0_1_2_protein.mol2 ../../dataset/protlig/3LT0_1_2_ligand.mol2 > extended/3LT0_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3LT1_1_2_protein.mol2 ../../dataset/protlig/3LT1_1_2_ligand.mol2 > extended/3LT1_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3LT4_1_2_protein.mol2 ../../dataset/protlig/3LT4_1_2_ligand.mol2 > extended/3LT4_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3LU7_1_1_protein.mol2 ../../dataset/protlig/3LU7_1_1_ligand.mol2 > extended/3LU7_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3MHC_1_1_protein.mol2 ../../dataset/protlig/3MHC_1_1_ligand.mol2 > extended/3MHC_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3N8X_1_2_protein.mol2 ../../dataset/protlig/3N8X_1_2_ligand.mol2 > extended/3N8X_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3NC2_1_1_protein.mol2 ../../dataset/protlig/3NC2_1_1_ligand.mol2 > extended/3NC2_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3NC2_1_3_protein.mol2 ../../dataset/protlig/3NC2_1_3_ligand.mol2 > extended/3NC2_1_3.ifp
IChem --extended IFP ../../dataset/protlig/3NCA_1_2_protein.mol2 ../../dataset/protlig/3NCA_1_2_ligand.mol2 > extended/3NCA_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3NLB_1_1_protein.mol2 ../../dataset/protlig/3NLB_1_1_ligand.mol2 > extended/3NLB_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3NNU_1_1_protein.mol2 ../../dataset/protlig/3NNU_1_1_ligand.mol2 > extended/3NNU_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3NTB_2_2_protein.mol2 ../../dataset/protlig/3NTB_2_2_ligand.mol2 > extended/3NTB_2_2.ifp
IChem --extended IFP ../../dataset/protlig/3NUS_1_5_protein.mol2 ../../dataset/protlig/3NUS_1_5_ligand.mol2 > extended/3NUS_1_5.ifp
IChem --extended IFP ../../dataset/protlig/3NUU_1_15_protein.mol2 ../../dataset/protlig/3NUU_1_15_ligand.mol2 > extended/3NUU_1_15.ifp
IChem --extended IFP ../../dataset/protlig/3ODK_1_2_protein.mol2 ../../dataset/protlig/3ODK_1_2_ligand.mol2 > extended/3ODK_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3OL5_1_2_protein.mol2 ../../dataset/protlig/3OL5_1_2_ligand.mol2 > extended/3OL5_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3OMO_2_1_protein.mol2 ../../dataset/protlig/3OMO_2_1_ligand.mol2 > extended/3OMO_2_1.ifp
IChem --extended IFP ../../dataset/protlig/3OMP_1_1_protein.mol2 ../../dataset/protlig/3OMP_1_1_ligand.mol2 > extended/3OMP_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3OMQ_1_1_protein.mol2 ../../dataset/protlig/3OMQ_1_1_ligand.mol2 > extended/3OMQ_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3ORZ_1_1_protein.mol2 ../../dataset/protlig/3ORZ_1_1_ligand.mol2 > extended/3ORZ_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3P0N_2_1_protein.mol2 ../../dataset/protlig/3P0N_2_1_ligand.mol2 > extended/3P0N_2_1.ifp
IChem --extended IFP ../../dataset/protlig/3P6O_1_2_protein.mol2 ../../dataset/protlig/3P6O_1_2_ligand.mol2 > extended/3P6O_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3PO7_1_2_protein.mol2 ../../dataset/protlig/3PO7_1_2_ligand.mol2 > extended/3PO7_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3Q32_2_1_protein.mol2 ../../dataset/protlig/3Q32_2_1_ligand.mol2 > extended/3Q32_2_1.ifp
IChem --extended IFP ../../dataset/protlig/3Q43_1_5_protein.mol2 ../../dataset/protlig/3Q43_1_5_ligand.mol2 > extended/3Q43_1_5.ifp
IChem --extended IFP ../../dataset/protlig/3Q92_1_3_protein.mol2 ../../dataset/protlig/3Q92_1_3_ligand.mol2 > extended/3Q92_1_3.ifp
IChem --extended IFP ../../dataset/protlig/3QA2_1_5_protein.mol2 ../../dataset/protlig/3QA2_1_5_ligand.mol2 > extended/3QA2_1_5.ifp
IChem --extended IFP ../../dataset/protlig/3QAI_1_5_protein.mol2 ../../dataset/protlig/3QAI_1_5_ligand.mol2 > extended/3QAI_1_5.ifp
IChem --extended IFP ../../dataset/protlig/3QGO_1_1_protein.mol2 ../../dataset/protlig/3QGO_1_1_ligand.mol2 > extended/3QGO_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3QYK_1_2_protein.mol2 ../../dataset/protlig/3QYK_1_2_ligand.mol2 > extended/3QYK_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3R00_1_2_protein.mol2 ../../dataset/protlig/3R00_1_2_ligand.mol2 > extended/3R00_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3R4M_1_1_protein.mol2 ../../dataset/protlig/3R4M_1_1_ligand.mol2 > extended/3R4M_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3R7U_1_2_protein.mol2 ../../dataset/protlig/3R7U_1_2_ligand.mol2 > extended/3R7U_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3R8M_1_2_protein.mol2 ../../dataset/protlig/3R8M_1_2_ligand.mol2 > extended/3R8M_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3ROC_1_1_protein.mol2 ../../dataset/protlig/3ROC_1_1_ligand.mol2 > extended/3ROC_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3RPS_1_1_protein.mol2 ../../dataset/protlig/3RPS_1_1_ligand.mol2 > extended/3RPS_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3RR3_1_5_protein.mol2 ../../dataset/protlig/3RR3_1_5_ligand.mol2 > extended/3RR3_1_5.ifp
IChem --extended IFP ../../dataset/protlig/3RYE_1_1_protein.mol2 ../../dataset/protlig/3RYE_1_1_ligand.mol2 > extended/3RYE_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3S0J_1_1_protein.mol2 ../../dataset/protlig/3S0J_1_1_ligand.mol2 > extended/3S0J_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3S2A_1_4_protein.mol2 ../../dataset/protlig/3S2A_1_4_ligand.mol2 > extended/3S2A_1_4.ifp
IChem --extended IFP ../../dataset/protlig/3S72_1_1_protein.mol2 ../../dataset/protlig/3S72_1_1_ligand.mol2 > extended/3S72_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3SL6_4_12_protein.mol2 ../../dataset/protlig/3SL6_4_12_ligand.mol2 > extended/3SL6_4_12.ifp
IChem --extended IFP ../../dataset/protlig/3SN7_1_2_protein.mol2 ../../dataset/protlig/3SN7_1_2_ligand.mol2 > extended/3SN7_1_2.ifp
IChem --extended IFP ../../dataset/protlig/3SNI_2_2_protein.mol2 ../../dataset/protlig/3SNI_2_2_ligand.mol2 > extended/3SNI_2_2.ifp
IChem --extended IFP ../../dataset/protlig/3T2J_1_6_protein.mol2 ../../dataset/protlig/3T2J_1_6_ligand.mol2 > extended/3T2J_1_6.ifp
IChem --extended IFP ../../dataset/protlig/3T8F_1_1_protein.mol2 ../../dataset/protlig/3T8F_1_1_ligand.mol2 > extended/3T8F_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3T8H_1_1_protein.mol2 ../../dataset/protlig/3T8H_1_1_ligand.mol2 > extended/3T8H_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3TC5_1_1_protein.mol2 ../../dataset/protlig/3TC5_1_1_ligand.mol2 > extended/3TC5_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3TZA_1_5_protein.mol2 ../../dataset/protlig/3TZA_1_5_ligand.mol2 > extended/3TZA_1_5.ifp
IChem --extended IFP ../../dataset/protlig/3U4U_1_1_protein.mol2 ../../dataset/protlig/3U4U_1_1_ligand.mol2 > extended/3U4U_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3UDJ_1_1_protein.mol2 ../../dataset/protlig/3UDJ_1_1_ligand.mol2 > extended/3UDJ_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3UIV_2_8_protein.mol2 ../../dataset/protlig/3UIV_2_8_ligand.mol2 > extended/3UIV_2_8.ifp
IChem --extended IFP ../../dataset/protlig/3UU7_1_1_protein.mol2 ../../dataset/protlig/3UU7_1_1_ligand.mol2 > extended/3UU7_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3UUA_1_1_protein.mol2 ../../dataset/protlig/3UUA_1_1_ligand.mol2 > extended/3UUA_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3W1T_1_1_protein.mol2 ../../dataset/protlig/3W1T_1_1_ligand.mol2 > extended/3W1T_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3W2M_1_18_protein.mol2 ../../dataset/protlig/3W2M_1_18_ligand.mol2 > extended/3W2M_1_18.ifp
IChem --extended IFP ../../dataset/protlig/3W3O_1_12_protein.mol2 ../../dataset/protlig/3W3O_1_12_ligand.mol2 > extended/3W3O_1_12.ifp
IChem --extended IFP ../../dataset/protlig/3WAR_1_1_protein.mol2 ../../dataset/protlig/3WAR_1_1_ligand.mol2 > extended/3WAR_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3WRL_2_2_protein.mol2 ../../dataset/protlig/3WRL_2_2_ligand.mol2 > extended/3WRL_2_2.ifp
IChem --extended IFP ../../dataset/protlig/3ZPQ_2_8_protein.mol2 ../../dataset/protlig/3ZPQ_2_8_ligand.mol2 > extended/3ZPQ_2_8.ifp
IChem --extended IFP ../../dataset/protlig/3ZPR_1_3_protein.mol2 ../../dataset/protlig/3ZPR_1_3_ligand.mol2 > extended/3ZPR_1_3.ifp
IChem --extended IFP ../../dataset/protlig/3ZPR_2_3_protein.mol2 ../../dataset/protlig/3ZPR_2_3_ligand.mol2 > extended/3ZPR_2_3.ifp
IChem --extended IFP ../../dataset/protlig/3ZRK_1_5_protein.mol2 ../../dataset/protlig/3ZRK_1_5_ligand.mol2 > extended/3ZRK_1_5.ifp
IChem --extended IFP ../../dataset/protlig/3ZRL_1_5_protein.mol2 ../../dataset/protlig/3ZRL_1_5_ligand.mol2 > extended/3ZRL_1_5.ifp
IChem --extended IFP ../../dataset/protlig/3ZVV_1_1_protein.mol2 ../../dataset/protlig/3ZVV_1_1_ligand.mol2 > extended/3ZVV_1_1.ifp
IChem --extended IFP ../../dataset/protlig/3ZYU_2_4_protein.mol2 ../../dataset/protlig/3ZYU_2_4_ligand.mol2 > extended/3ZYU_2_4.ifp
IChem --extended IFP ../../dataset/protlig/4A2Z_1_2_protein.mol2 ../../dataset/protlig/4A2Z_1_2_ligand.mol2 > extended/4A2Z_1_2.ifp
IChem --extended IFP ../../dataset/protlig/4A30_1_3_protein.mol2 ../../dataset/protlig/4A30_1_3_ligand.mol2 > extended/4A30_1_3.ifp
IChem --extended IFP ../../dataset/protlig/4A31_1_2_protein.mol2 ../../dataset/protlig/4A31_1_2_ligand.mol2 > extended/4A31_1_2.ifp
IChem --extended IFP ../../dataset/protlig/4A9L_1_4_protein.mol2 ../../dataset/protlig/4A9L_1_4_ligand.mol2 > extended/4A9L_1_4.ifp
IChem --extended IFP ../../dataset/protlig/4AQC_1_1_protein.mol2 ../../dataset/protlig/4AQC_1_1_ligand.mol2 > extended/4AQC_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4AWQ_1_1_protein.mol2 ../../dataset/protlig/4AWQ_1_1_ligand.mol2 > extended/4AWQ_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4BUT_1_3_protein.mol2 ../../dataset/protlig/4BUT_1_3_ligand.mol2 > extended/4BUT_1_3.ifp
IChem --extended IFP ../../dataset/protlig/4BUU_2_1_protein.mol2 ../../dataset/protlig/4BUU_2_1_ligand.mol2 > extended/4BUU_2_1.ifp
IChem --extended IFP ../../dataset/protlig/4D3J_1_3_protein.mol2 ../../dataset/protlig/4D3J_1_3_ligand.mol2 > extended/4D3J_1_3.ifp
IChem --extended IFP ../../dataset/protlig/4DWB_1_5_protein.mol2 ../../dataset/protlig/4DWB_1_5_ligand.mol2 > extended/4DWB_1_5.ifp
IChem --extended IFP ../../dataset/protlig/4DXJ_2_2_protein.mol2 ../../dataset/protlig/4DXJ_2_2_ligand.mol2 > extended/4DXJ_2_2.ifp
IChem --extended IFP ../../dataset/protlig/4E4M_2_1_protein.mol2 ../../dataset/protlig/4E4M_2_1_ligand.mol2 > extended/4E4M_2_1.ifp
IChem --extended IFP ../../dataset/protlig/4EDZ_2_4_protein.mol2 ../../dataset/protlig/4EDZ_2_4_ligand.mol2 > extended/4EDZ_2_4.ifp
IChem --extended IFP ../../dataset/protlig/4EEQ_1_4_protein.mol2 ../../dataset/protlig/4EEQ_1_4_ligand.mol2 > extended/4EEQ_1_4.ifp
IChem --extended IFP ../../dataset/protlig/4EFB_1_4_protein.mol2 ../../dataset/protlig/4EFB_1_4_ligand.mol2 > extended/4EFB_1_4.ifp
IChem --extended IFP ../../dataset/protlig/4EFE_1_4_protein.mol2 ../../dataset/protlig/4EFE_1_4_ligand.mol2 > extended/4EFE_1_4.ifp
IChem --extended IFP ../../dataset/protlig/4ENY_1_4_protein.mol2 ../../dataset/protlig/4ENY_1_4_ligand.mol2 > extended/4ENY_1_4.ifp
IChem --extended IFP ../../dataset/protlig/4F08_2_1_protein.mol2 ../../dataset/protlig/4F08_2_1_ligand.mol2 > extended/4F08_2_1.ifp
IChem --extended IFP ../../dataset/protlig/4FAD_1_1_protein.mol2 ../../dataset/protlig/4FAD_1_1_ligand.mol2 > extended/4FAD_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4FM5_1_4_protein.mol2 ../../dataset/protlig/4FM5_1_4_ligand.mol2 > extended/4FM5_1_4.ifp
IChem --extended IFP ../../dataset/protlig/4G1X_1_9_protein.mol2 ../../dataset/protlig/4G1X_1_9_ligand.mol2 > extended/4G1X_1_9.ifp
IChem --extended IFP ../../dataset/protlig/4G44_1_5_protein.mol2 ../../dataset/protlig/4G44_1_5_ligand.mol2 > extended/4G44_1_5.ifp
IChem --extended IFP ../../dataset/protlig/4G46_1_6_protein.mol2 ../../dataset/protlig/4G46_1_6_ligand.mol2 > extended/4G46_1_6.ifp
IChem --extended IFP ../../dataset/protlig/4GCA_1_2_protein.mol2 ../../dataset/protlig/4GCA_1_2_ligand.mol2 > extended/4GCA_1_2.ifp
IChem --extended IFP ../../dataset/protlig/4GFM_1_1_protein.mol2 ../../dataset/protlig/4GFM_1_1_ligand.mol2 > extended/4GFM_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4GIY_1_1_protein.mol2 ../../dataset/protlig/4GIY_1_1_ligand.mol2 > extended/4GIY_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4GR0_1_1_protein.mol2 ../../dataset/protlig/4GR0_1_1_ligand.mol2 > extended/4GR0_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4H57_1_1_protein.mol2 ../../dataset/protlig/4H57_1_1_ligand.mol2 > extended/4H57_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4H5D_1_1_protein.mol2 ../../dataset/protlig/4H5D_1_1_ligand.mol2 > extended/4H5D_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4H5E_1_1_protein.mol2 ../../dataset/protlig/4H5E_1_1_ligand.mol2 > extended/4H5E_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4H84_1_1_protein.mol2 ../../dataset/protlig/4H84_1_1_ligand.mol2 > extended/4H84_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4H84_2_1_protein.mol2 ../../dataset/protlig/4H84_2_1_ligand.mol2 > extended/4H84_2_1.ifp
IChem --extended IFP ../../dataset/protlig/4HAI_1_2_protein.mol2 ../../dataset/protlig/4HAI_1_2_ligand.mol2 > extended/4HAI_1_2.ifp
IChem --extended IFP ../../dataset/protlig/4HBV_1_3_protein.mol2 ../../dataset/protlig/4HBV_1_3_ligand.mol2 > extended/4HBV_1_3.ifp
IChem --extended IFP ../../dataset/protlig/4HXP_1_1_protein.mol2 ../../dataset/protlig/4HXP_1_1_ligand.mol2 > extended/4HXP_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4IAA_1_1_protein.mol2 ../../dataset/protlig/4IAA_1_1_ligand.mol2 > extended/4IAA_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4IPW_1_6_protein.mol2 ../../dataset/protlig/4IPW_1_6_ligand.mol2 > extended/4IPW_1_6.ifp
IChem --extended IFP ../../dataset/protlig/4J71_1_1_protein.mol2 ../../dataset/protlig/4J71_1_1_ligand.mol2 > extended/4J71_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4J71_2_1_protein.mol2 ../../dataset/protlig/4J71_2_1_ligand.mol2 > extended/4J71_2_1.ifp
IChem --extended IFP ../../dataset/protlig/4JNC_1_1_protein.mol2 ../../dataset/protlig/4JNC_1_1_ligand.mol2 > extended/4JNC_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4K5N_1_3_protein.mol2 ../../dataset/protlig/4K5N_1_3_ligand.mol2 > extended/4K5N_1_3.ifp
IChem --extended IFP ../../dataset/protlig/4K5O_1_3_protein.mol2 ../../dataset/protlig/4K5O_1_3_ligand.mol2 > extended/4K5O_1_3.ifp
IChem --extended IFP ../../dataset/protlig/4K5P_1_3_protein.mol2 ../../dataset/protlig/4K5P_1_3_ligand.mol2 > extended/4K5P_1_3.ifp
IChem --extended IFP ../../dataset/protlig/4KLV_1_15_protein.mol2 ../../dataset/protlig/4KLV_1_15_ligand.mol2 > extended/4KLV_1_15.ifp
IChem --extended IFP ../../dataset/protlig/4KLW_1_1_protein.mol2 ../../dataset/protlig/4KLW_1_1_ligand.mol2 > extended/4KLW_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4KOR_1_1_protein.mol2 ../../dataset/protlig/4KOR_1_1_ligand.mol2 > extended/4KOR_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4KOS_1_1_protein.mol2 ../../dataset/protlig/4KOS_1_1_ligand.mol2 > extended/4KOS_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4KOX_1_5_protein.mol2 ../../dataset/protlig/4KOX_1_5_ligand.mol2 > extended/4KOX_1_5.ifp
IChem --extended IFP ../../dataset/protlig/4KZ0_1_1_protein.mol2 ../../dataset/protlig/4KZ0_1_1_ligand.mol2 > extended/4KZ0_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4KZ3_2_1_protein.mol2 ../../dataset/protlig/4KZ3_2_1_ligand.mol2 > extended/4KZ3_2_1.ifp
IChem --extended IFP ../../dataset/protlig/4KZA_1_4_protein.mol2 ../../dataset/protlig/4KZA_1_4_ligand.mol2 > extended/4KZA_1_4.ifp
IChem --extended IFP ../../dataset/protlig/4KZA_2_3_protein.mol2 ../../dataset/protlig/4KZA_2_3_ligand.mol2 > extended/4KZA_2_3.ifp
IChem --extended IFP ../../dataset/protlig/4L17_1_1_protein.mol2 ../../dataset/protlig/4L17_1_1_ligand.mol2 > extended/4L17_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4LH6_1_1_protein.mol2 ../../dataset/protlig/4LH6_1_1_ligand.mol2 > extended/4LH6_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4LH7_1_1_protein.mol2 ../../dataset/protlig/4LH7_1_1_ligand.mol2 > extended/4LH7_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4LKQ_1_1_protein.mol2 ../../dataset/protlig/4LKQ_1_1_ligand.mol2 > extended/4LKQ_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4LLJ_1_1_protein.mol2 ../../dataset/protlig/4LLJ_1_1_ligand.mol2 > extended/4LLJ_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4M10_1_4_protein.mol2 ../../dataset/protlig/4M10_1_4_ligand.mol2 > extended/4M10_1_4.ifp
IChem --extended IFP ../../dataset/protlig/4M10_2_5_protein.mol2 ../../dataset/protlig/4M10_2_5_ligand.mol2 > extended/4M10_2_5.ifp
IChem --extended IFP ../../dataset/protlig/4MQ1_4_1_protein.mol2 ../../dataset/protlig/4MQ1_4_1_ligand.mol2 > extended/4MQ1_4_1.ifp
IChem --extended IFP ../../dataset/protlig/4MTA_1_1_protein.mol2 ../../dataset/protlig/4MTA_1_1_ligand.mol2 > extended/4MTA_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4MVH_1_8_protein.mol2 ../../dataset/protlig/4MVH_1_8_ligand.mol2 > extended/4MVH_1_8.ifp
IChem --extended IFP ../../dataset/protlig/4NIE_1_1_protein.mol2 ../../dataset/protlig/4NIE_1_1_ligand.mol2 > extended/4NIE_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4O1Z_1_4_protein.mol2 ../../dataset/protlig/4O1Z_1_4_ligand.mol2 > extended/4O1Z_1_4.ifp
IChem --extended IFP ../../dataset/protlig/4O76_3_1_protein.mol2 ../../dataset/protlig/4O76_3_1_ligand.mol2 > extended/4O76_3_1.ifp
IChem --extended IFP ../../dataset/protlig/4OAD_1_5_protein.mol2 ../../dataset/protlig/4OAD_1_5_ligand.mol2 > extended/4OAD_1_5.ifp
IChem --extended IFP ../../dataset/protlig/4P0V_1_1_protein.mol2 ../../dataset/protlig/4P0V_1_1_ligand.mol2 > extended/4P0V_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4PNM_3_1_protein.mol2 ../../dataset/protlig/4PNM_3_1_ligand.mol2 > extended/4PNM_3_1.ifp
IChem --extended IFP ../../dataset/protlig/4PUK_1_4_protein.mol2 ../../dataset/protlig/4PUK_1_4_ligand.mol2 > extended/4PUK_1_4.ifp
IChem --extended IFP ../../dataset/protlig/4Q4E_1_1_protein.mol2 ../../dataset/protlig/4Q4E_1_1_ligand.mol2 > extended/4Q4E_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4Q4M_1_1_protein.mol2 ../../dataset/protlig/4Q4M_1_1_ligand.mol2 > extended/4Q4M_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4UCM_1_2_protein.mol2 ../../dataset/protlig/4UCM_1_2_ligand.mol2 > extended/4UCM_1_2.ifp
IChem --extended IFP ../../dataset/protlig/4UCP_1_1_protein.mol2 ../../dataset/protlig/4UCP_1_1_ligand.mol2 > extended/4UCP_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4UG5_1_4_protein.mol2 ../../dataset/protlig/4UG5_1_4_ligand.mol2 > extended/4UG5_1_4.ifp
IChem --extended IFP ../../dataset/protlig/4UG7_1_4_protein.mol2 ../../dataset/protlig/4UG7_1_4_ligand.mol2 > extended/4UG7_1_4.ifp
IChem --extended IFP ../../dataset/protlig/4UQR_1_3_protein.mol2 ../../dataset/protlig/4UQR_1_3_ligand.mol2 > extended/4UQR_1_3.ifp
IChem --extended IFP ../../dataset/protlig/4UQS_1_3_protein.mol2 ../../dataset/protlig/4UQS_1_3_ligand.mol2 > extended/4UQS_1_3.ifp
IChem --extended IFP ../../dataset/protlig/4UVE_1_2_protein.mol2 ../../dataset/protlig/4UVE_1_2_ligand.mol2 > extended/4UVE_1_2.ifp
IChem --extended IFP ../../dataset/protlig/4UVL_1_3_protein.mol2 ../../dataset/protlig/4UVL_1_3_ligand.mol2 > extended/4UVL_1_3.ifp
IChem --extended IFP ../../dataset/protlig/4UYD_1_3_protein.mol2 ../../dataset/protlig/4UYD_1_3_ligand.mol2 > extended/4UYD_1_3.ifp
IChem --extended IFP ../../dataset/protlig/4UYF_2_2_protein.mol2 ../../dataset/protlig/4UYF_2_2_ligand.mol2 > extended/4UYF_2_2.ifp
IChem --extended IFP ../../dataset/protlig/4XN7_1_1_protein.mol2 ../../dataset/protlig/4XN7_1_1_ligand.mol2 > extended/4XN7_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4XNA_1_1_protein.mol2 ../../dataset/protlig/4XNA_1_1_ligand.mol2 > extended/4XNA_1_1.ifp
IChem --extended IFP ../../dataset/protlig/4YKW_2_1_protein.mol2 ../../dataset/protlig/4YKW_2_1_ligand.mol2 > extended/4YKW_2_1.ifp
IChem --extended IFP ../../dataset/protlig/4YO4_1_7_protein.mol2 ../../dataset/protlig/4YO4_1_7_ligand.mol2 > extended/4YO4_1_7.ifp
IChem --extended IFP ../../dataset/protlig/4YPD_1_3_protein.mol2 ../../dataset/protlig/4YPD_1_3_ligand.mol2 > extended/4YPD_1_3.ifp
IChem --extended IFP ../../dataset/protlig/4ZSM_2_1_protein.mol2 ../../dataset/protlig/4ZSM_2_1_ligand.mol2 > extended/4ZSM_2_1.ifp
IChem --extended IFP ../../dataset/protlig/5A3X_2_1_protein.mol2 ../../dataset/protlig/5A3X_2_1_ligand.mol2 > extended/5A3X_2_1.ifp
IChem --extended IFP ../../dataset/protlig/5A54_3_1_protein.mol2 ../../dataset/protlig/5A54_3_1_ligand.mol2 > extended/5A54_3_1.ifp
IChem --extended IFP ../../dataset/protlig/5AG7_1_1_protein.mol2 ../../dataset/protlig/5AG7_1_1_ligand.mol2 > extended/5AG7_1_1.ifp
IChem --extended IFP ../../dataset/protlig/5AI5_1_3_protein.mol2 ../../dataset/protlig/5AI5_1_3_ligand.mol2 > extended/5AI5_1_3.ifp
IChem --extended IFP ../../dataset/protlig/5AKJ_1_8_protein.mol2 ../../dataset/protlig/5AKJ_1_8_ligand.mol2 > extended/5AKJ_1_8.ifp
IChem --extended IFP ../../dataset/protlig/5AKZ_1_7_protein.mol2 ../../dataset/protlig/5AKZ_1_7_ligand.mol2 > extended/5AKZ_1_7.ifp
IChem --extended IFP ../../dataset/protlig/5ALU_1_4_protein.mol2 ../../dataset/protlig/5ALU_1_4_ligand.mol2 > extended/5ALU_1_4.ifp
IChem --extended IFP ../../dataset/protlig/5AUW_1_1_protein.mol2 ../../dataset/protlig/5AUW_1_1_ligand.mol2 > extended/5AUW_1_1.ifp
IChem --extended IFP ../../dataset/protlig/5C29_1_1_protein.mol2 ../../dataset/protlig/5C29_1_1_ligand.mol2 > extended/5C29_1_1.ifp
IChem --extended IFP ../../dataset/protlig/5CLP_2_2_protein.mol2 ../../dataset/protlig/5CLP_2_2_ligand.mol2 > extended/5CLP_2_2.ifp
IChem --extended IFP ../../dataset/protlig/5EVD_1_1_protein.mol2 ../../dataset/protlig/5EVD_1_1_ligand.mol2 > extended/5EVD_1_1.ifp
IChem --extended IFP ../../dataset/protlig/5EVK_1_1_protein.mol2 ../../dataset/protlig/5EVK_1_1_ligand.mol2 > extended/5EVK_1_1.ifp
IChem --extended IFP ../../dataset/protlig/5FNK_1_3_protein.mol2 ../../dataset/protlig/5FNK_1_3_ligand.mol2 > extended/5FNK_1_3.ifp
IChem --extended IFP ../../dataset/protlig/5G42_1_1_protein.mol2 ../../dataset/protlig/5G42_1_1_ligand.mol2 > extended/5G42_1_1.ifp
IChem --extended IFP ../../dataset/protlig/5G44_1_3_protein.mol2 ../../dataset/protlig/5G44_1_3_ligand.mol2 > extended/5G44_1_3.ifp
IChem --extended IFP ../../dataset/protlig/5G45_1_1_protein.mol2 ../../dataset/protlig/5G45_1_1_ligand.mol2 > extended/5G45_1_1.ifp
